---
name: 'Build arm images'

on:
  push:
    branches:
      - 770-push-arm-images-to-own-repo
    tags:
      - '*'

jobs:
  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch --prune --unshallow
    - id: set-matrix
      run: |
          content=`cat ./releases-arm.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=matrix::{\"include\": $content }"

  docker:
    runs-on: ubuntu-latest
    needs:
    - get-matrix
    permissions:
      id-token: write  # OIDC support
      contents: write
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.get-matrix.outputs.matrix)}}
    steps:
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build  🔧
        env:
          FLAVOR: ${{ matrix.flavor }}
          MODEL: ${{ matrix.model }}
        run: |
          ./earthly.sh +all-arm --MODEL=$MODEL --FLAVOR=$FLAVOR --K3S_VERSION=${{ matrix.k3s_version }}
      - name: Push  🔧
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo $(cat build/IMAGE)
          docker push $(cat build/IMAGE)
      - name: Sign image
        if: startsWith(github.ref, 'refs/tags/')
        env:
          COSIGN_YES: true
        run: |
          export IMAGE=$(cat build/IMAGE)
          cosign sign $(docker images "$IMAGE" --format  "{{.Digest}}")
      - name: Upload Image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl https://luet.io/install.sh | sudo sh
          IMG=$(cat build/IMAGE).img
          sudo tar cvf build.tar build
          sudo luet util pack $IMG build.tar image.tar
          sudo -E docker load -i image.tar
          echo quay.io/kairos/kairos-${{ matrix.flavor }}-img:${{ matrix.k3s_version }}
          sudo -E docker push quay.io/kairos/kairos-${{ matrix.flavor }}-img:${{ matrix.k3s_version }}.img
          sudo rm -rf build/IMAGE build/VERSION
